.TH notmuch-address-cache 1 "Sep 2017" "version v0.1"

.SH NAME
notmuch-address-cache - caches the result from notmuch-address and search within this cached version.

.SH SYNOPSIS
.B notmuch-address-cache
[ 
.I COMMAND 
] 
[ 
.I ARG 
]

.SH DESCRIPTION

.B notmuch-address-cache
is basically a cache in front of the 
.I notmuch-address
command.

notmuch-address-cache caches all sender and recipients you communicated with. It expect the notmuch tag \fbtag:all\fP on all messages to extract the sender and recipients from there. You can configure notmuch to apply the \fBtag:all\fP to all messages. This is basically done if you edit the file \fI~/.notmuch-config\fP, go into section [new] and add the value \fBall\fP to the key \fBtags\fP.

.SH Commands

.TP
\fBhelp\fP, \fB--help\fP, \fB-h\fP
Show help text.
.TP
\fBversion\fP, \fB--version\fP, \fB-v\fP
Show the version.
.TP
\fBrebuild\fP, \fB--rebuild\fP, \fB-r\fP [\fB--json\fP | \fB--text\fP]
Uses \fInotmuch-address\fP to find all sender/recipient you communicated with and print them out to the file \fI~/.notmuch-address-cache/addresses\fP. The format of the cached addresses are stored in json, if you rebuild your cache with option \fB--json\fP. The format of the cached addresses are stored in text, if you rebuild your cache with option\fB--text\fP. Format text is recommended if you want to query the cache with \fBmutt\fP. Format json is recommended if you want to query the cache with \fBalot\fP.
.TP
\fBquery\fP, \fB--query\fP, \fB-q\fP
greps bla bla
